import { Ubuntu } from "next/font/google"; // Import the Ubuntu font
import "./globals.css"; // Import global CSS

// Initialize the Ubuntu font with subsets and weights
const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Result Aayo", // Title for the application
  description: "Generated by create next app", // Description for the application
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} dark:bg-medium`}>
       
        <div>       
      {children}
        </div>
      </body>
    </html>
  );
}
